# Site settings
title: deploy everyday
email: jonatas.baldin@gmail.com
description: livin' and sysadminin'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonatasbaldin.github.io" # the base hostname & protocol for your site
twitter_username: vuashhhh
github_username:  jonatasbaldin

# Build settings
markdown: redcarpet

paginate: 10
