# Site settings
title: deploy everyday
email: jonatas.baldin@gmail.com
description: my journey in cloud, automation and system administration
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deployeveryday.com" # the base hostname & protocol for your site
twitter_username: vuashhhh
github_username:  jonatasbaldin

# Build settings
markdown: redcarpet

# Pagination
paginate: 10

gems:
  - jekyll-sitemap
