# Setup
title:               Deploy Everyday
tagline:             'my journey on the Internets (mainly dev and ops stuff)'
description:         "Hi, you've just entered in my cool vortex. Here I talk about my computer adventures. I sometimes have a life, so you may read about it. You can yell at me clicking in the icons below." 
url:                 http://deployeveryday.com
baseurl:             ''
paginate:            10
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: jonatasbaldin

# About/contact
author:
  name:              Jonatas Baldin
  url:               https://twitter.com/jonatasbaldin
  twitter:           https://twitter.com/jonatasbaldin
  twitter_username:  jonatasbaldin
  github:            https://github.com/jonatasbaldin
  linkedin:          https://br.linkedin.com/in/jonatasbaldin
  email:             jonatas.baldin@gmail.com

plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
