# Setup
title:               Deploy Everyday
tagline:             'my journey in cloud, automation and system administration'
description:         "Hi, you've just entered in my cool vortex. Here I talk about automation, cloud, system administration and develepoment. I sometimes have a life, so you may read about it. You can yell at me clicking in the icons below." 
url:                 http://deployeveryday.com
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Jonatas Baldin
  url:               https://twitter.com/jonatasbaldin
  twitter:           https://twitter.com/jonatasbaldin
  twitter_username:  jonatasbaldin
  github:            https://github.com/jonatasbaldin
  linkedin:          https://br.linkedin.com/in/jonatasbaldin
  email:             jonatas.baldin@gmail.com

gems: [jekyll-paginate, jekyll-sitemap, jekyll-gist]
