# Setup
title:               Deploy Everyday
tagline:             'my journey on Life & Internets'
description:         "Hi, I'm Jojo. I travel and I do Internet stuff. Here I talk about my life and computer adventures. You can yell at me clicking in the icons below." 
url:                 http://deployeveryday.com
baseurl:             ''
paginate:            10
markdown: kramdown
highlighter: rouge

# Disqus
comments: True

# SEO
twitter:
  username: jonatasbaldin

# About/contact
author:
  name:              Jonatas Baldin
  url:               https://twitter.com/jonatasbaldin
  twitter:           https://twitter.com/jonatasbaldin
  twitter_username:  jonatasbaldin
  github:            https://github.com/jonatasbaldin
  linkedin:          https://br.linkedin.com/in/jonatasbaldin
  email:             jonatas.baldin@gmail.com
  youtube:           https://www.youtube.com/channel/UCSckSM5vayBNNTl4nKuAUPg

plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
